### ISSUE TITLE
Issue regarding the generation of Galaxy Collision Simulations

### ISSUE THREAD

**Issue by Astrofest** [rcburnet/Gravitational-N-Body-problems#1]
Attempts were conducted to produce a couple galaxy collisions with 500 particles (title of video file adjusted accordingly). However, the following line of text appeared: "MovieWriter ffmpeg unavailable; using Pillow instead." This led to the following error to occur: 
"Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/PIL/Image.py", line 2082, in save
    format = EXTENSION[ext]
KeyError: '.mp4'
"
Afterwards, another exception occurred, in which the following lines produced an error: 
"galcol.animate('rk4_parabolic_orbit_500_particles_counterclockwise')" 
and 
"line_ani.save(filename+'.mp4', fps = 60, bitrate=7200)"
The final line of produced diagnostic remains: "ValueError: unknown file extension: .mp4"

This occurred regardless of my installing FFmpeg via homebrew and pip. Please assist whenever possible. And apologies for wasting time, if I am.

**Comment by rcburnet** [comment]
Hey,

Try saving it as a gif instead. You'll need to change the following line
from:

line_ani.save(filename+'.mp4', fps = 60, bitrate=7200)

To:

line_ani.save(filename+'.gif', writer = 'PillowWriter', fps = 60,
bitrate=7200)

See if that helps

Robert

**Comment by Astrofest** [comment]
Issue has been resolved. Thank you very much for your time.
